---
version: "3"
services:
  netbootxyz:
    container_name: netbootxyz
    image: linuxserver/netbootxyz:latest
    network_mode: "host"
    volumes:
      - ./data/config:/config
      - ./data/assets:/assets
  dnsmasq:
    build:
      context: dnsmasq
    environment:
      - DHCP_RANGE_START=${SUBNET:-192.168.1.1}
      - WEB_APP_PORT=${WEB_APP_PORT:-3000}
    network_mode: "host"
    cap_add:
      - NET_ADMIN

